# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Sakura blog'
tagline:       	  'Retro hardware and what not'
description:      'News and stories from development of new hardware by Sakura.'
url: 		  http://blog.sakura-it.pl/
baseurl: 	  http://blog.sakura-it.pl/

author:
  name:           'Radoslaw Kujawa'
  url:            http://sakura-it.pl

paginate:         5


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Sakura-IT/blog

